import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
import { Imprima } from "next/font/google";

const roboto = Imprima({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "St-Gulf-Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
  
        {children}
      </body>
    </html>
  );
}
